version: "3"

networks:
    gallifrey:
    
services:
    riversong:
        image: {{registry}}/tardis/riversong
        ports:
            - 8888:8888
        networks:
            - gallifrey
        deploy:
            replicas: 2
            labels: [apptype=internal]
    thedoctor:
        image: {{registry}}/tardis/thedoctor
        ports:
            - 80:80
        networks:
            - gallifrey
        deploy:
            replicas: 2
            labels: [apptype=edge]
        environment:
            - INTERNAL_SERVICE_NAME=riversong
